AllCops:
    TargetRubyVersion: 2.4
Style/FrozenStringLiteralComment:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Metrics/LineLength:
    Enabled: false
Style/Documentation:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: true
    Exclude:
      - test/**/*
Metrics/MethodLength:
    Enabled: true
    Exclude:
      - test/**/*
